language: python
python:
  - "2.7"
before_install:
  - pip install coveralls 
  - pip install nose 
  - pip install rednose 
install:
  - python setup.py install
script: nosetests test/
after_success:
  - coveralls
